name: Cpp CI

on: 
    push:
        branches: [ main ]
jobs:
    test:
      name: "Tests"
      strategy:
        fail-fast: false
        matrix:
          include:
            - name: Linux GCC
              os: ubuntu-latest
              compiler: g++-9
  
            - name: Linux Clang
              os: ubuntu-latest
              compiler: clang++
  
            - name: MacOS clang
              os: macos-latest
              compiler: clang++
  
            - name: Windows MSVC
              os: windows-latest
              compiler: cl
  
      runs-on: ${{ matrix.os }}
      steps:
        - name: "Checkout repository"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
  
        - name: "Enable MSVC command prompt"
          if: matrix.os == 'windows-latest'
          uses: ilammy/msvc-dev-cmd@v1
  
        - name: "Install cmake"
          uses: lukka/get-cmake@latest
  
        - name: "Build debug mode"
          run: >
            cd cpp;
            mkdir build;
            cd build;
            cmake ..
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
            -DCMAKE_BUILD_TYPE=Debug;
            cmake --build . --target test_money;

        - name: "Run the Tests on windows"
          if: matrix.os == 'windows-latest'
          run: > 
            cd cpp;
            test_money;
        
        - name: "Run the Test On Ubuntu & MacOS"
          if: matrix.os != 'windows-latest'
          run: > 
            cd cpp/build;
            ./test_money;